(function(){
  'use strict';
  var app=document.getElementById('app'), token='', busy=false;
  var labels={PAID:['ชำระแล้ว','paid'],UNPAID:['ยังไม่ชำระ','unpaid'],LEAVE:['วันลา','leave'],UPCOMING:['ยังไม่ถึงกำหนด','upcoming'],NO_RECORD:['วันนี้ไม่มีรายการเรียกเก็บค่าเช่า','no-record']};
  function esc(value){var node=document.createElement('span');node.textContent=value==null?'':String(value);return node.innerHTML;}
  function status(key){var item=labels[key]||labels.NO_RECORD;return '<span class="status '+item[1]+'">'+item[0]+'</span>';}
  function call(action,params){
    if(busy)return Promise.reject(new Error('มีคำขอกำลังดำเนินการอยู่'));
    busy=true; params=params||{}; params.api=action; params.id_token=token;
    return new Promise(function(resolve,reject){
      var name='jsonp_'+Date.now()+'_'+Math.random().toString(36).slice(2), script=document.createElement('script');
      params.callback=name; window[name]=function(result){cleanup();resolve(result);};
      function cleanup(){busy=false;delete window[name];if(script.parentNode)script.parentNode.removeChild(script);}
      script.onerror=function(){cleanup();reject(new Error('เชื่อมต่อเซิร์ฟเวอร์ไม่สำเร็จ'));};
      script.src=window.APP_CONFIG.apiUrl+'?'+Object.keys(params).map(function(key){return encodeURIComponent(key)+'='+encodeURIComponent(params[key]);}).join('&');
      document.body.appendChild(script);
      setTimeout(function(){if(window[name]){cleanup();reject(new Error('เซิร์ฟเวอร์ไม่ตอบสนองภายใน 15 วินาที'));}},15000);
    });
  }
  function showError(message,code){var detail=code?' ['+code+']':'';app.innerHTML='<div class="shell"><div class="error">'+esc(message||'เกิดข้อผิดพลาด กรุณาลองใหม่ภายหลัง')+esc(detail)+'</div><button class="button" id="retry">ลองใหม่</button></div>';document.getElementById('retry').onclick=boot;}
  function registration(){app.innerHTML='<div class="shell"><section class="panel"><p class="eyebrow">เริ่มต้นใช้งาน</p><h1 class="title">ลงทะเบียนผู้เช่าพื้นที่</h1><p class="muted">กรุณากรอกรหัสลงทะเบียนจากเจ้าหน้าที่</p><label for="code">รหัสลงทะเบียน</label><input id="code" class="input" maxlength="32" autocomplete="one-time-code"><div class="actions" style="margin-top:14px"><button class="button" id="register">ยืนยัน</button></div></section></div>';document.getElementById('register').onclick=async function(){var button=document.getElementById('register');button.disabled=true;try{var result=await call('register',{code:document.getElementById('code').value});if(!result.success){showError(result.error.message,result.error.code);button.disabled=false;return;}await loadDashboard();}catch(error){button.disabled=false;showError(error.message);}};}
  function dashboard(data){var t=data.today;app.innerHTML='<div class="shell"><header class="header"><div><p class="eyebrow">ค่าเช่ารายวันโรงอาหาร</p><h1 class="title">'+esc(data.shop.shopName)+'</h1></div><button class="button secondary" id="refresh">รีเฟรช</button></header><section class="panel hero"><p class="muted">วันนี้ '+esc(t.displayDate)+'</p><div>'+status(t.status)+'</div><div class="amount">'+(t.amount?esc(t.amount.toLocaleString('th-TH'))+' บาท':'-')+'</div></section><section class="panel"><h2>สรุปเดือนนี้</h2><div class="summary"><div class="metric">ชำระแล้ว<strong>'+data.summary.paidDays+' วัน</strong></div><div class="metric">ยังไม่ชำระ<strong>'+data.summary.unpaidDays+' วัน</strong></div><div class="metric">วันลา<strong>'+data.summary.leaveDays+' วัน</strong></div><div class="metric">ยังไม่ถึงกำหนด<strong>'+data.summary.futureDays+' วัน</strong></div><div class="metric">ยอดชำระแล้ว<strong>'+data.summary.paidAmount.toLocaleString('th-TH')+' บาท</strong></div><div class="metric">ยอดยังไม่ชำระ<strong>'+data.summary.unpaidAmount.toLocaleString('th-TH')+' บาท</strong></div></div></section><section class="panel"><div class="actions"><button class="button" id="history">ดูประวัติการชำระ</button><button class="button secondary" id="contact">ติดต่อเจ้าหน้าที่</button></div><p class="muted">อัปเดตล่าสุด '+esc(data.updatedAt)+' น.</p></section></div>';document.getElementById('refresh').onclick=loadDashboard;document.getElementById('history').onclick=loadHistory;document.getElementById('contact').onclick=function(){alert('กรุณาติดต่อเจ้าหน้าที่ผ่าน LINE Official Account');};}
  async function loadDashboard(){app.innerHTML='<div class="loading">กำลังโหลดข้อมูล...</div>';try{var result=await call('dashboard');if(!result.success){if(result.error.code==='USER_NOT_REGISTERED')return registration();throw new Error(result.error.message);}dashboard(result.data);}catch(error){showError(error.message);}}
  async function loadHistory(){app.innerHTML='<div class="loading">กำลังโหลดประวัติ...</div>';try{var months=await call('months');if(!months.success)throw new Error(months.error.message);var current=months.data[months.data.length-1]&&months.data[months.data.length-1].id;var history=await call('history',{month:current});if(!history.success)throw new Error(history.error.message);var options=months.data.map(function(month){return '<option value="'+esc(month.id)+'">'+esc(month.label)+'</option>';}).join('');app.innerHTML='<div class="shell"><header class="header"><h1 class="title">ประวัติการชำระ</h1><button class="button secondary" id="back">กลับ</button></header><select class="select" id="month" aria-label="เลือกเดือน">'+options+'</select><section class="panel" id="items"></section></div>';function render(items){document.getElementById('items').innerHTML=items.length?items.map(function(item){return '<div class="history-item"><div><strong>'+esc(item.displayDate)+'</strong><div>'+status(item.status)+'</div></div><div class="right">'+(item.amount?esc(item.amount.toLocaleString('th-TH'))+' บาท':'')+(item.receivedDate?'<div class="muted">รับเงิน '+esc(item.receivedDate)+'</div>':'')+'</div></div>';}).join(''):'<p class="muted">ยังไม่มีข้อมูลค่าเช่าในเดือนนี้</p>';};render(history.data.items);document.getElementById('month').onchange=async function(event){var result=await call('history',{month:event.target.value});if(result.success)render(result.data.items);};document.getElementById('back').onclick=loadDashboard;}catch(error){showError(error.message);}}
  async function boot(){app.innerHTML='<div class="loading">กำลังเข้าสู่ระบบ...</div>';try{if(!window.APP_CONFIG.liffId||!window.APP_CONFIG.apiUrl)throw new Error('ยังไม่ได้ตั้งค่าระบบ');await liff.init({liffId:window.APP_CONFIG.liffId});if(!liff.isLoggedIn()){liff.login();return;}app.innerHTML='<div class="loading">กำลังตรวจสอบบัญชี...</div>';token=liff.getIDToken();if(!token)throw new Error('ไม่สามารถยืนยันตัวตนได้ กรุณาอนุญาตการเข้าสู่ระบบ LINE');await loadDashboard();}catch(error){showError(error.message);}}
  boot();
})();
